### ISSUE TITLE
ImportError: No module named 'acoustid_priv_tools'

### ISSUE THREAD

**Issue by netradiofrance** [acoustid/acoustid-priv-tools#1]
Hello

Impossible to import music catalog with acoustid-priv-sync -d /pathtomymusicmp3files

I got : ImportError: No module named 'acoustid_priv_tools'

Same error with : acoustid-priv-monitor -o 'acoustid-results-stream1-%Y-%m-%d-%H.csv' http://mystreamurl.mp3

I got : ImportError: No module named 'acoustid_priv_tools'

Any solution please ?

Thanks

**Comment by lalinsky** [comment]
This should be fixed after https://github.com/acoustid/acoustid-priv-tools/commit/101f6af675fbd60e6042692be8c57b4c0db8d286, you will need to reinstall it.
