### ISSUE TITLE
Issue stop monitor with special caracters

### ISSUE THREAD

**Issue by netradiofrance** [acoustid/acoustid-priv-tools#3]
I have found an issue with special caracters. That's stop monitoring !

2 exemples :

root@ns394035:/opt/acoustid-priv-tools/bin# ./acoustid-priv-monitor -o '/home/TRACKING/netradiofrance-%Y-%m-%d-%H.csv' http://netradio.ice.infomaniak.ch/netradio-128.mp3
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track 2DZKKeSrmckB1z-G-qqnL0nJ0DxKOkSxFx81R6N1aAM (Tommy Cct - Plead The Blood)
INFO: Found track RLG0Aw78DHUblfrTeNC32Bn8Xk4x04HGt3KbFUYAHx4 (**Misska - Adultère Imaginaire**)
Traceback (most recent call last):
  File "./acoustid-priv-monitor", line 11, in <module>
    load_entry_point('acoustid-priv-tools==0.1', 'console_scripts', 'acoustid-priv-monitor')()
  File "/opt/acoustid-priv-tools/local/lib/python2.7/site-packages/acoustid_priv_tools/monitor.py", line 149, in main
    'title': track['metadata'].get('title'),
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128)
root@ns394035:/opt/acoustid-priv-tools/bin#

root@ns394035:/opt/acoustid-priv-tools/bin# ./acoustid-priv-monitor -o '/home/TRACKING/rpl-%Y-%m-%d-%H.csv' http://91.121.120.162:8000/rpl.mp3
INFO: Found track Z_RjvGclnWcUXEmEvQ3ZtddpNuagRzOQ27saEoVMpJo (Larry Carlton & SWR Big Band - Too Young To Go Steady)
INFO: Found track 32guC3ujQZtJLbXpMtBB8uiHhS2MJ2gKEnLs3lMEmOM (Leon Triplett - Motown)
INFO: Found track X0EZ0YTzcQZ5UliWVEBRbt48cFK3FPzgMfSKqKGUrXs (**Marion GUERIN - Un Père**)
Traceback (most recent call last):
  File "./acoustid-priv-monitor", line 11, in <module>
    load_entry_point('acoustid-priv-tools==0.1', 'console_scripts', 'acoustid-priv-monitor')()
  File "/opt/acoustid-priv-tools/local/lib/python2.7/site-packages/acoustid_priv_tools/monitor.py", line 149, in main
    'title': track['metadata'].get('title'),
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 4: ordinal not in range(128)
root@ns394035:/opt/acoustid-priv-tools/bin#

Can you check this please ?

Thanks for your precious help

**Comment by lalinsky** [comment]
I'm sorry about that. It should be fixed in the latest version. You will need to reinstall the package with `pip`.
